CREATE TABLE `agents` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`name` varchar(255) NOT NULL,
	`description` text,
	`dna` varchar(255) NOT NULL,
	`wallet` varchar(255) NOT NULL,
	`type` varchar(64) NOT NULL,
	`tokenSymbol` varchar(10) NOT NULL,
	`tokenName` varchar(255) NOT NULL,
	`totalSupply` varchar(255) NOT NULL,
	`decimals` int NOT NULL DEFAULT 18,
	`network` varchar(64) NOT NULL DEFAULT 'base',
	`status` enum('created','deployed','active','paused','archived') NOT NULL DEFAULT 'created',
	`githubUsername` varchar(255),
	`githubRepository` varchar(255),
	`contractAddress` varchar(255),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `agents_id` PRIMARY KEY(`id`),
	CONSTRAINT `agents_dna_unique` UNIQUE(`dna`),
	CONSTRAINT `agents_wallet_unique` UNIQUE(`wallet`),
	CONSTRAINT `agents_tokenSymbol_unique` UNIQUE(`tokenSymbol`)
);
